Fine tuning (again) of tvpowerd installation and installations scripts

diff --git a/trunk/src/tvpowerd/install.sh.in b/trunk/src/tvpowerd/install.sh.in
--- a/trunk/src/tvpowerd/install.sh.in
+++ b/trunk/src/tvpowerd/install.sh.in
@@ -3,6 +3,11 @@
 #$Id$
 #DON'T EDIT : @configure_input@
 
+#--------------------------------------------------------------
+# The output variables eill be processed by the configure
+# script so that the shell variables will be set according to
+# the users specifications.
+#--------------------------------------------------------------
 PACKAGE_TARNAME=tvpowerd
 sysconfdir=@sysconfdir@
 prefix=@prefix@
@@ -16,8 +21,10 @@ top_srcdir=@top_srcdir@
 manpages=${top_srcdir}/docs/manpages/
 datarootdir=@datarootdir@
 
-#First a sanity check so that the user doesn't try to install tvpowerd on the
-#same server where he/she is running tvpvrd
+#--------------------------------------------------------------
+#First a sanity check so that the user doesn't try to install 
+# tvpowerd on the #same server where he/she is running tvpvrd
+#--------------------------------------------------------------
 if test -f ${bindir}/tvpvrd; then
     echo "The tvpowerd daemon is supposed to be installed on a different server than tvpvrd."
     echo "Installation aborted."
@@ -30,7 +37,10 @@ if test ! -w ${sysconfdir}; then
     exit 1;
 fi
 
-# Install configuration scripts
+#--------------------------------------------------------------
+# Install configuration scripts. But check so we don't overwrite
+# any existing scripts.
+#--------------------------------------------------------------
 if test -f ${sysconfdir}/tvpowerd/tvpowerd.conf; then
 	echo "----------------------------------------------";
 	echo "Will not overwrite existing tvpowerd.conf file !";
@@ -43,16 +53,35 @@ else
     fi
 fi
 
-install -D -m 755 pre-shutdown.sh ${sysconfdir}/tvpowerd/pre-shutdown.sh > /dev/null 2>&1 && \
-install -D -m 755 post-startup.sh ${sysconfdir}/tvpowerd/post-startup.sh > /dev/null 2>&1 
-if test ! $? = 0; then
-    echo "Failed to install configuration scripts"
-    exit 1
+if test -f ${sysconfdir}/tvpowerd/pre-shutdown.sh; then
+	echo "----------------------------------------------";
+	echo "Will not overwrite existing pre-shutdown.sh file !";
+	echo "----------------------------------------------";
+else
+    install -D -m 755 pre-shutdown.sh ${sysconfdir}/tvpowerd/pre-shutdown.sh > /dev/null 2>&1
+    if test ! $? = 0; then
+        echo "Failed to install pre-shutdown.sh configuration script"
+        exit 1
+    fi
 fi
 
+if test -f ${sysconfdir}/tvpowerd/post-startup.sh; then
+	echo "----------------------------------------------";
+	echo "Will not overwrite existing post-startup.sh file !";
+	echo "----------------------------------------------";
+else
+    install -D -m 755 post-startup.sh ${sysconfdir}/tvpowerd/post-startup.sh > /dev/null 2>&1
+    if test ! $? = 0; then
+        echo "Failed to install post-startup.sh configuration script"
+        exit 1
+    fi
+fi
+
+#--------------------------------------------------------------
 #install service starting scripts
+#--------------------------------------------------------------
 if test -f /etc/rc.status; then
-    install -m 755 init.d.tvpowerd ${sysconfdir}/init.d/tvpowerd > /dev/null 2>&1 
+   install -m 755 init.d.tvpowerd ${sysconfdir}/init.d/tvpowerd > /dev/null 2>&1 
 else
    install -m 755 deb.init.d.tvpowerd ${sysconfdir}/init.d/tvpowerd > /dev/null 2>&1 
 fi
@@ -60,18 +89,21 @@ if test ! $? = 0; then
     echo "Failed to install service scripts"
     exit 1
 fi
-
+#--------------------------------------------------------------
 #install the binary
-if test -f ${bindir}/tvpowerd; then
+#--------------------------------------------------------------
+if test -f ${sysconfdir}/init.d/tvpowerd; then
     ${sysconfdir}/init.d/tvpowerd stop;
 fi
 install -m 755 tvpowerd ${bindir}/tvpowerd > /dev/null 2>&1 
 if test ! $? = 0; then
-    echo "Failed to install binary ! (Is the existing version running?)"
+    echo "Failed to install daemon binary file"
     exit 1
 fi
 
+#--------------------------------------------------------------
 #install man pages
+#--------------------------------------------------------------
 install -D -m 644 ${manpages}/tvpowerd.1 ${mandir}/man1/tvpowerd.1 > /dev/null 2>&1 && \
 install -D -m 644 ${manpages}/tvpowerd.1.pdf ${docdir}/tvpowerd.1.pdf > /dev/null 2>&1 && \
 install -D -m 644 ${manpages}/tvpowerd.1.html ${docdir}/tvpowerd.1.html > /dev/null 2>&1 
